
try {
    TryTest.method1();
}
catch(Exception e) {
    System.println(e.message);
    System.println("CATCH EXCEPTION");
}

