print("try test...");
try {
    1/0;
}
catch(e:Exception) {
    println("OK");
}
